### ISSUE TITLE
nodejs

### ISSUE THREAD

**Issue by leostera** [dotnetwise/Javascript-FastClass#2]
Hi there,

I was trying to use this within nodejs but I ran into the issue of whether it was safe or not to remove the WAsserts and still have both the functionality and performance this lib offers.

Thanks!

**Comment by dotnetwise** [comment]
I will publish a node version soon.

**Comment by leostera** [comment]
I wouldn't mind helping out.

On Fri, Oct 11, 2013 at 5:43 AM, dotnetwise notifications@github.comwrote:

> I will publish a node version soon.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dotnetwise/Javascript-FastClass/issues/2#issuecomment-26122614
> .

## 

Leandro Ostera
Web Engineer

I hack at github.com/leostera
I talk on skype as leostera
I tweet as @leostera http://twitter.com/leostera
I blog at blog.leostera.com
I network at angel.co/leostera
I video at vimeo.com/leostera
I play bass at soundcloud.com/leostera
I'm also on linkedin.com/in/leostera
And yeah, I need a new signature.

**Comment by dotnetwise** [comment]
:+1:  Thanks. Some testing would be nice.

https://npmjs.org/package/fast-class

#### Install

You can install it either globally with the `-g` switch or locally

```
npm install fast-class -g
```

#### Usage:

``` javascript
require('fast-class');
var F = Function.define(function() {
//my ctor
...
}, {
   someProtoMethod: function() {
      console.log("I'm on A");
   },
});
var G = F.inheritWith(function(base,baseCtor) {
    return {
        constructor: function() {
            baseCtor.apply(this, arguments)
        },
        someProtoMethod: function() {
            console.log("I'm on B");
            base.someProtoMethod.apply(this, arguments);
        }
});
```

Enjoy!

**Comment by leostera** [comment]
Thanks @dotnetwise :)
